import { AcademyDataset } from "@/modules/academy-data/types";

export const academyDataset: AcademyDataset = {
  tenantId: "cca-main",
  productArea: "academy",
  generatedAt: "2026-04-23T09:00:00.000Z",
  institutionName: "ChurchCore Academy",
  administrators: [
    { id: "user-regina", tenantId: "cca-main", name: "Regina Holt", title: "Registrar", role: "registrar" },
    { id: "user-adrian", tenantId: "cca-main", name: "Adrian Wells", title: "Admissions Director", role: "admissions" },
    { id: "user-miriam", tenantId: "cca-main", name: "Miriam Stone", title: "Academic Dean", role: "dean" },
    { id: "user-julian", tenantId: "cca-main", name: "Julian Pace", title: "Academic Advisor", role: "advisor" },
    { id: "user-sophia", tenantId: "cca-main", name: "Sophia Marsh", title: "Academic Administrator", role: "academic_admin" },
  ],
  programs: [
    {
      id: "prog-biblical-studies",
      tenantId: "cca-main",
      name: "B.A. Biblical Studies",
      credential: "bachelor",
      requiredCredits: 120,
      cohortLabel: "Spring 2026 Degree Cohort",
    },
    {
      id: "prog-ministry-leadership",
      tenantId: "cca-main",
      name: "A.A. Ministry Leadership",
      credential: "associate",
      requiredCredits: 60,
      cohortLabel: "Fall 2026 Cohort",
    },
  ],
  students: [
    {
      id: "stu-maya-bennett",
      tenantId: "cca-main",
      fullName: "Maya Bennett",
      email: "maya.bennett@churchcoreacademy.edu",
      enrollmentStatus: "pending",
      applicationStartedAt: "2026-03-28T12:00:00.000Z",
      missingEnrollmentSteps: ["Program assignment", "Advisor assignment", "Final registration confirmation"],
      missingDocuments: ["application_form"],
      documentationNotes: ["Admissions intake checklist is incomplete."],
      creditsEarned: 0,
      expectedCreditsByNow: 0,
      transcriptCredits: 0,
      statusFlag: "pending_review",
      allProgramCoursesCompleted: false,
      graduationAdministrativeHolds: [],
      expectedNextTermRegistered: false,
      transcriptAlerts: [],
      recordAlerts: ["Admitted status has not been posted even though application review is complete."],
    },
    {
      id: "stu-ezra-coleman",
      tenantId: "cca-main",
      fullName: "Ezra Coleman",
      email: "ezra.coleman@churchcoreacademy.edu",
      enrollmentStatus: "admitted",
      admittedAt: "2026-04-02T14:00:00.000Z",
      programId: "prog-ministry-leadership",
      advisorUserId: "user-julian",
      missingEnrollmentSteps: ["Registration agreement"],
      missingDocuments: ["government_id", "prior_transcript", "consent_agreement"],
      documentationNotes: [
        "Transfer transcript has not been received from prior institution.",
        "Student agreement packet remains unsigned.",
      ],
      creditsEarned: 0,
      expectedCreditsByNow: 0,
      transcriptCredits: 0,
      statusFlag: "pending_review",
      allProgramCoursesCompleted: false,
      graduationAdministrativeHolds: [],
      expectedNextTermRegistered: false,
      transcriptAlerts: [],
      recordAlerts: [],
    },
    {
      id: "stu-naomi-price",
      tenantId: "cca-main",
      fullName: "Naomi Price",
      email: "naomi.price@churchcoreacademy.edu",
      enrollmentStatus: "active",
      admittedAt: "2022-08-19T15:00:00.000Z",
      activeTerm: "Spring 2026",
      programId: "prog-biblical-studies",
      advisorUserId: "user-julian",
      missingEnrollmentSteps: [],
      missingDocuments: [],
      documentationNotes: [],
      creditsEarned: 117,
      expectedCreditsByNow: 114,
      transcriptCredits: 117,
      gpa: 3.42,
      statusFlag: "good_standing",
      allProgramCoursesCompleted: true,
      graduationAdministrativeHolds: ["Diploma request confirmation pending"],
      expectedNextTermRegistered: false,
      transcriptAlerts: [],
      recordAlerts: [],
    },
    {
      id: "stu-daniel-hart",
      tenantId: "cca-main",
      fullName: "Daniel Hart",
      email: "daniel.hart@churchcoreacademy.edu",
      enrollmentStatus: "active",
      admittedAt: "2024-01-11T13:00:00.000Z",
      activeTerm: "Spring 2026",
      programId: "prog-biblical-studies",
      advisorUserId: "user-julian",
      missingEnrollmentSteps: [],
      missingDocuments: [],
      documentationNotes: [],
      creditsEarned: 31,
      expectedCreditsByNow: 45,
      transcriptCredits: 31,
      gpa: 1.94,
      statusFlag: "probation",
      allProgramCoursesCompleted: false,
      graduationAdministrativeHolds: [],
      expectedNextTermRegistered: false,
      transcriptAlerts: ["Two incomplete course outcomes remain unresolved."],
      recordAlerts: [],
    },
    {
      id: "stu-leah-brooks",
      tenantId: "cca-main",
      fullName: "Leah Brooks",
      email: "leah.brooks@churchcoreacademy.edu",
      enrollmentStatus: "active",
      admittedAt: "2023-08-15T10:00:00.000Z",
      activeTerm: "Spring 2026",
      programId: "prog-ministry-leadership",
      advisorUserId: "user-julian",
      missingEnrollmentSteps: [],
      missingDocuments: [],
      documentationNotes: [],
      creditsEarned: 48,
      expectedCreditsByNow: 48,
      transcriptCredits: 51,
      gpa: 3.11,
      statusFlag: "good_standing",
      allProgramCoursesCompleted: false,
      graduationAdministrativeHolds: [],
      expectedNextTermRegistered: true,
      transcriptAlerts: [
        "Recorded transcript credits exceed posted program progress by 3 credits.",
        "New Testament Survey appears twice with different completion statuses.",
      ],
      recordAlerts: ["Primary student status and degree audit flag disagree."],
    },
  ],
  faculty: [
    {
      id: "fac-miriam-stone",
      tenantId: "cca-main",
      name: "Miriam Stone",
      title: "Professor of Biblical Studies",
      assignedSectionIds: ["sec-nt401", "sec-ot315", "sec-th210", "sec-ch301", "sec-min210"],
      adviseeCount: 31,
    },
    {
      id: "fac-samuel-reed",
      tenantId: "cca-main",
      name: "Samuel Reed",
      title: "Adjunct Faculty",
      assignedSectionIds: ["sec-ml205"],
      adviseeCount: 8,
    },
  ],
  sections: [
    {
      id: "sec-nt401",
      tenantId: "cca-main",
      code: "NT-401",
      title: "Pauline Epistles",
      programId: "prog-biblical-studies",
      instructorFacultyId: "fac-miriam-stone",
      rosterCount: 29,
      rosterCapacity: 24,
      setupAlerts: [],
    },
    {
      id: "sec-ml205",
      tenantId: "cca-main",
      code: "ML-205",
      title: "Pastoral Administration",
      programId: "prog-ministry-leadership",
      rosterCount: 22,
      rosterCapacity: 20,
      setupAlerts: ["Section syllabus upload pending"],
    },
    {
      id: "sec-cap490",
      tenantId: "cca-main",
      code: "CAP-490",
      title: "Capstone Seminar",
      programId: "prog-biblical-studies",
      rosterCount: 16,
      rosterCapacity: 18,
      setupAlerts: ["No instructor assigned"],
    },
  ],
  thresholds: {
    incompleteEnrollmentDays: 10,
    graduationCreditThreshold: 0.95,
    creditPaceGap: 9,
    minimumGpa: 2,
    facultyLoadThreshold: 4,
    advisorStudentRatioThreshold: 25,
  },
};

export const academyNow = new Date(academyDataset.generatedAt);
