import { AcademyDataset } from "@/modules/academy-data/types";
import { createInstitutionProfileDefaults } from "@/modules/academy-config/defaults";

export const academyDataset: AcademyDataset = {
  tenantId: "cca-main",
  productArea: "academy",
  generatedAt: "2026-04-23T09:00:00.000Z",
  institutionName: "ChurchCore Academy",
  institutionProfile: createInstitutionProfileDefaults({
    tenantId: "cca-main",
    institutionName: "ChurchCore Academy",
    legalName: "ChurchCore Academy",
    primaryMode: "mixed",
    supportedModes: ["mixed", "bible_school", "childrens_school", "seminary", "college", "university"],
    lmsProvider: "none",
    now: "2026-04-23T09:00:00.000Z",
  }),
  academicCalendar: {
    institutionProfile: createInstitutionProfileDefaults({
      tenantId: "cca-main",
      institutionName: "ChurchCore Academy",
      legalName: "ChurchCore Academy",
      primaryMode: "mixed",
      supportedModes: ["mixed", "bible_school", "childrens_school", "seminary", "college", "university"],
      lmsProvider: "none",
      now: "2026-04-23T09:00:00.000Z",
    }),
    calendarProfile: {
      tenantId: "cca-main",
      calendarSystem: "rolling_enrollment",
      defaultTermStructure: "module",
      timezone: "America/New_York",
      weekStartsOn: "monday",
      usesInstructionalDays: true,
      usesEnrollmentWindows: true,
      usesGradingWindows: true,
      usesTranscriptPeriods: true,
      createdAt: "2026-04-23T09:00:00.000Z",
      updatedAt: "2026-04-23T09:00:00.000Z",
    },
    subdivisions: [
      {
        id: "branch-bible-school",
        tenantId: "cca-main",
        name: "Bible School",
        code: "BIBLE",
        subdivisionType: "school",
        institutionMode: "bible_school",
        status: "active",
        createdAt: "2026-04-23T09:00:00.000Z",
        updatedAt: "2026-04-23T09:00:00.000Z",
      },
      {
        id: "branch-childrens-school",
        tenantId: "cca-main",
        name: "Children's School",
        code: "CHILD",
        subdivisionType: "school",
        institutionMode: "childrens_school",
        status: "active",
        createdAt: "2026-04-23T09:00:00.000Z",
        updatedAt: "2026-04-23T09:00:00.000Z",
      },
      {
        id: "branch-seminary",
        tenantId: "cca-main",
        name: "Seminary",
        code: "SEM",
        subdivisionType: "school",
        institutionMode: "seminary",
        status: "active",
        createdAt: "2026-04-23T09:00:00.000Z",
        updatedAt: "2026-04-23T09:00:00.000Z",
      },
      {
        id: "branch-college",
        tenantId: "cca-main",
        name: "College",
        code: "COL",
        subdivisionType: "school",
        institutionMode: "college",
        status: "active",
        createdAt: "2026-04-23T09:00:00.000Z",
        updatedAt: "2026-04-23T09:00:00.000Z",
      },
      {
        id: "branch-university",
        tenantId: "cca-main",
        name: "University",
        code: "UNI",
        subdivisionType: "school",
        institutionMode: "university",
        status: "active",
        createdAt: "2026-04-23T09:00:00.000Z",
        updatedAt: "2026-04-23T09:00:00.000Z",
      },
      {
        id: "grade-band-k5",
        tenantId: "cca-main",
        parentSubdivisionId: "branch-childrens-school",
        name: "K-5",
        code: "K5",
        subdivisionType: "grade_band",
        institutionMode: "childrens_school",
        status: "active",
        createdAt: "2026-04-23T09:00:00.000Z",
        updatedAt: "2026-04-23T09:00:00.000Z",
      },
      {
        id: "cohort-ministry-2026",
        tenantId: "cca-main",
        parentSubdivisionId: "branch-bible-school",
        name: "Ministry Training 2026",
        code: "MIN2026",
        subdivisionType: "cohort",
        institutionMode: "bible_school",
        status: "active",
        createdAt: "2026-04-23T09:00:00.000Z",
        updatedAt: "2026-04-23T09:00:00.000Z",
      },
    ],
    academicYears: [
      {
        id: "year-ministry-2026",
        tenantId: "cca-main",
        name: "2026 Ministry Training Reporting Year",
        code: "MIN2026",
        startsOn: "2026-01-01",
        endsOn: "2026-12-31",
        status: "active",
        calendarSystem: "rolling_enrollment",
        subdivisionId: "branch-bible-school",
        createdAt: "2026-04-23T09:00:00.000Z",
        updatedAt: "2026-04-23T09:00:00.000Z",
      },
      {
        id: "year-childrens-2026",
        tenantId: "cca-main",
        name: "2026-2027 School Year",
        code: "SY2026",
        startsOn: "2026-08-15",
        endsOn: "2027-05-31",
        status: "active",
        calendarSystem: "school_year",
        subdivisionId: "branch-childrens-school",
        createdAt: "2026-04-23T09:00:00.000Z",
        updatedAt: "2026-04-23T09:00:00.000Z",
      },
    ],
    periods: [
      {
        id: "module-acts-2026",
        tenantId: "cca-main",
        academicYearId: "year-ministry-2026",
        subdivisionId: "branch-bible-school",
        name: "Acts Ministry Module",
        code: "ACTS",
        periodType: "module",
        startsOn: "2026-04-01",
        endsOn: "2026-05-15",
        sequence: 1,
        status: "active",
        createdAt: "2026-04-23T09:00:00.000Z",
        updatedAt: "2026-04-23T09:00:00.000Z",
      },
      {
        id: "trimester-fall-2026",
        tenantId: "cca-main",
        academicYearId: "year-childrens-2026",
        subdivisionId: "branch-childrens-school",
        name: "Fall Trimester",
        code: "FALL",
        periodType: "term",
        startsOn: "2026-08-15",
        endsOn: "2026-11-20",
        sequence: 1,
        status: "draft",
        createdAt: "2026-04-23T09:00:00.000Z",
        updatedAt: "2026-04-23T09:00:00.000Z",
      },
    ],
    enrollmentWindows: [
      {
        id: "rolling-application-acts",
        tenantId: "cca-main",
        academicPeriodId: "module-acts-2026",
        windowType: "application",
        opensAt: "2026-03-01T00:00:00.000Z",
        closesAt: null,
        createdAt: "2026-04-23T09:00:00.000Z",
        updatedAt: "2026-04-23T09:00:00.000Z",
      },
    ],
    gradingWindows: [
      {
        id: "grading-acts",
        tenantId: "cca-main",
        academicPeriodId: "module-acts-2026",
        opensAt: "2026-05-16T00:00:00.000Z",
        closesAt: "2026-05-31T23:59:59.000Z",
        gradePostingPolicy: "registrar_posting",
        createdAt: "2026-04-23T09:00:00.000Z",
        updatedAt: "2026-04-23T09:00:00.000Z",
      },
    ],
    transcriptPeriods: [
      {
        id: "completion-acts",
        tenantId: "cca-main",
        academicPeriodId: "module-acts-2026",
        recordType: "completion_record",
        postingOpensAt: "2026-06-01T00:00:00.000Z",
        postingClosesAt: "2026-06-15T23:59:59.000Z",
        createdAt: "2026-04-23T09:00:00.000Z",
        updatedAt: "2026-04-23T09:00:00.000Z",
      },
    ],
  },
  courseCatalog: {
    institutionProfile: createInstitutionProfileDefaults({
      tenantId: "cca-main",
      institutionName: "ChurchCore Academy",
      legalName: "ChurchCore Academy",
      primaryMode: "bible_school",
      supportedModes: ["bible_school", "childrens_school"],
      lmsProvider: "none",
      now: "2026-04-23T09:00:00.000Z",
    }),
    catalogProfile: {
      tenantId: "cca-main",
      defaultCourseRecordType: "completion_record",
      defaultDurationUnit: "clock_hour",
      supportsCredits: false,
      supportsClockHours: true,
      supportsCompetencies: false,
      supportsNarrativeEvaluation: true,
      supportsGradeLevels: true,
      supportsLmsMapping: false,
      createdAt: "2026-04-23T09:00:00.000Z",
      updatedAt: "2026-04-23T09:00:00.000Z",
    },
    academicYears: [
      {
        id: "year-ministry-2026",
        tenantId: "cca-main",
        name: "2026 Ministry Training Reporting Year",
        code: "MIN2026",
        startsOn: "2026-01-01",
        endsOn: "2026-12-31",
        status: "active",
        calendarSystem: "rolling_enrollment",
        subdivisionId: "branch-bible-school",
        createdAt: "2026-04-23T09:00:00.000Z",
        updatedAt: "2026-04-23T09:00:00.000Z",
      },
      {
        id: "year-childrens-2026",
        tenantId: "cca-main",
        name: "2026-2027 School Year",
        code: "SY2026",
        startsOn: "2026-08-15",
        endsOn: "2027-05-31",
        status: "active",
        calendarSystem: "school_year",
        subdivisionId: "branch-childrens-school",
        createdAt: "2026-04-23T09:00:00.000Z",
        updatedAt: "2026-04-23T09:00:00.000Z",
      },
    ],
    academicPeriods: [
      {
        id: "module-acts-2026",
        tenantId: "cca-main",
        academicYearId: "year-ministry-2026",
        subdivisionId: "branch-bible-school",
        name: "Acts Ministry Module",
        code: "ACTS",
        periodType: "module",
        startsOn: "2026-04-01",
        endsOn: "2026-05-15",
        sequence: 1,
        status: "active",
        createdAt: "2026-04-23T09:00:00.000Z",
        updatedAt: "2026-04-23T09:00:00.000Z",
      },
      {
        id: "trimester-fall-2026",
        tenantId: "cca-main",
        academicYearId: "year-childrens-2026",
        subdivisionId: "branch-childrens-school",
        name: "Fall Trimester",
        code: "FALL",
        periodType: "term",
        startsOn: "2026-08-15",
        endsOn: "2026-11-20",
        sequence: 1,
        status: "draft",
        createdAt: "2026-04-23T09:00:00.000Z",
        updatedAt: "2026-04-23T09:00:00.000Z",
      },
    ],
    subdivisions: [
      {
        id: "branch-bible-school",
        tenantId: "cca-main",
        name: "Bible School",
        code: "BIBLE",
        subdivisionType: "school",
        institutionMode: "bible_school",
        status: "active",
        createdAt: "2026-04-23T09:00:00.000Z",
        updatedAt: "2026-04-23T09:00:00.000Z",
      },
      {
        id: "branch-childrens-school",
        tenantId: "cca-main",
        name: "Children's School",
        code: "CHILD",
        subdivisionType: "school",
        institutionMode: "childrens_school",
        status: "active",
        createdAt: "2026-04-23T09:00:00.000Z",
        updatedAt: "2026-04-23T09:00:00.000Z",
      },
      {
        id: "grade-band-k5",
        tenantId: "cca-main",
        parentSubdivisionId: "branch-childrens-school",
        name: "K-5",
        code: "K5",
        subdivisionType: "grade_band",
        institutionMode: "childrens_school",
        status: "active",
        createdAt: "2026-04-23T09:00:00.000Z",
        updatedAt: "2026-04-23T09:00:00.000Z",
      },
      {
        id: "cohort-ministry-2026",
        tenantId: "cca-main",
        parentSubdivisionId: "branch-bible-school",
        name: "Ministry Training 2026",
        code: "MIN2026",
        subdivisionType: "cohort",
        institutionMode: "bible_school",
        status: "active",
        createdAt: "2026-04-23T09:00:00.000Z",
        updatedAt: "2026-04-23T09:00:00.000Z",
      },
    ],
    courses: [
      {
        id: "course-acts-ministry",
        tenantId: "cca-main",
        code: "ACTS-MIN",
        title: "Acts Ministry Module",
        description: "Ministry formation module focused on Acts and local church mission.",
        courseType: "bible_course",
        courseLevel: "certificate",
        recordType: "completion_record",
        defaultDuration: {
          durationUnit: "clock_hour",
          durationValue: 24,
          clockHours: 24,
        },
        defaultClockHours: 24,
        owningSubdivisionId: "branch-bible-school",
        status: "active",
        createdAt: "2026-04-23T09:00:00.000Z",
        updatedAt: "2026-04-23T09:00:00.000Z",
      },
      {
        id: "course-reading-k5",
        tenantId: "cca-main",
        code: "READ-K5",
        title: "Reading Foundations",
        description: "Children's school reading class with progress-record evaluation.",
        courseType: "children_class",
        courseLevel: "children",
        recordType: "progress_record",
        defaultDuration: {
          durationUnit: "week",
          durationValue: 16,
        },
        gradeBandSubdivisionId: "grade-band-k5",
        status: "active",
        createdAt: "2026-04-23T09:00:00.000Z",
        updatedAt: "2026-04-23T09:00:00.000Z",
      },
      {
        id: "course-ministry-practicum",
        tenantId: "cca-main",
        code: "MIN-390",
        title: "Supervised Ministry Practicum",
        description: "Field practicum for supervised ministry service and reflection.",
        courseType: "ministry_practicum",
        courseLevel: "certificate",
        recordType: "completion_record",
        defaultDuration: {
          durationUnit: "clock_hour",
          durationValue: 45,
          clockHours: 45,
        },
        defaultClockHours: 45,
        owningSubdivisionId: "branch-bible-school",
        status: "active",
        createdAt: "2026-04-23T09:00:00.000Z",
        updatedAt: "2026-04-23T09:00:00.000Z",
      },
      {
        id: "course-chapel",
        tenantId: "cca-main",
        code: "CHAPEL",
        title: "Chapel",
        description: "Institution-wide chapel attendance record.",
        courseType: "chapel",
        courseLevel: "mixed",
        recordType: "attendance_only",
        defaultDuration: {
          durationUnit: "week",
          durationValue: 16,
        },
        status: "active",
        createdAt: "2026-04-23T09:00:00.000Z",
        updatedAt: "2026-04-23T09:00:00.000Z",
      },
    ],
    sections: [
      {
        id: "section-acts-ministry",
        tenantId: "cca-main",
        courseId: "course-acts-ministry",
        academicYearId: "year-ministry-2026",
        academicPeriodId: "module-acts-2026",
        subdivisionId: "cohort-ministry-2026",
        sectionCode: "ACTS-MIN-1",
        deliveryMode: "hybrid",
        schedulePattern: "Tuesday 6:30 PM",
        capacity: 24,
        status: "open",
        primaryInstructorRole: "instructor",
        primaryInstructorId: "user-miriam",
        assistantInstructorIds: [],
        createdAt: "2026-04-23T09:00:00.000Z",
        updatedAt: "2026-04-23T09:00:00.000Z",
      },
      {
        id: "section-reading-k5",
        tenantId: "cca-main",
        courseId: "course-reading-k5",
        academicYearId: "year-childrens-2026",
        academicPeriodId: "trimester-fall-2026",
        subdivisionId: "grade-band-k5",
        sectionCode: "READ-K5-A",
        deliveryMode: "in_person",
        schedulePattern: "Daily reading block",
        capacity: 18,
        status: "scheduled",
        primaryInstructorRole: "teacher",
        primaryInstructorId: "user-sophia",
        assistantInstructorIds: [],
        createdAt: "2026-04-23T09:00:00.000Z",
        updatedAt: "2026-04-23T09:00:00.000Z",
      },
      {
        id: "section-ministry-practicum",
        tenantId: "cca-main",
        courseId: "course-ministry-practicum",
        academicYearId: "year-ministry-2026",
        academicPeriodId: "module-acts-2026",
        subdivisionId: "branch-bible-school",
        sectionCode: "MIN-390-A",
        deliveryMode: "field_practicum",
        schedulePattern: "Supervised field placement",
        capacity: 12,
        status: "scheduled",
        primaryInstructorRole: "instructor",
        primaryInstructorId: "user-miriam",
        assistantInstructorIds: [],
        createdAt: "2026-04-23T09:00:00.000Z",
        updatedAt: "2026-04-23T09:00:00.000Z",
      },
    ],
    prerequisites: [],
    lmsMappings: [
      {
        id: "mapping-no-lms-acts",
        tenantId: "cca-main",
        courseId: "course-acts-ministry",
        sectionId: "section-acts-ministry",
        provider: "none",
        mappingStatus: "not_required",
        syncPolicy: "manual",
        lastReviewedAt: "2026-04-23T09:00:00.000Z",
        createdAt: "2026-04-23T09:00:00.000Z",
        updatedAt: "2026-04-23T09:00:00.000Z",
      },
    ],
  },
  gradingRecords: {
    institutionProfile: createInstitutionProfileDefaults({
      tenantId: "cca-main",
      institutionName: "ChurchCore Academy",
      legalName: "ChurchCore Academy",
      primaryMode: "mixed",
      supportedModes: ["mixed", "bible_school", "childrens_school"],
      lmsProvider: "none",
      now: "2026-04-23T09:00:00.000Z",
    }),
    gradingProfile: {
      tenantId: "cca-main",
      defaultEvaluationType: "pass_fail",
      defaultOfficialRecordType: "completion_record",
      supportsGpa: false,
      supportsCredits: false,
      supportsClockHours: true,
      supportsCompetencies: true,
      supportsNarrativeEvaluation: true,
      supportsPromotion: true,
      supportsGraduationAudit: true,
      gradeReleasePolicy: "registrar_release",
      guardianVisibilityPolicy: "not_applicable",
      createdAt: "2026-04-23T09:00:00.000Z",
      updatedAt: "2026-04-23T09:00:00.000Z",
    },
    scales: [
      {
        id: "scale-ministry-pass-fail",
        tenantId: "cca-main",
        name: "Ministry Completion Pass Fail",
        scaleType: "pass_fail",
        appliesToRecordType: "completion_record",
        status: "active",
        createdAt: "2026-04-23T09:00:00.000Z",
        updatedAt: "2026-04-23T09:00:00.000Z",
      },
    ],
    scaleBands: [
      {
        id: "band-ministry-pass",
        tenantId: "cca-main",
        scaleId: "scale-ministry-pass-fail",
        label: "Pass",
        isPassing: true,
        isCompletion: true,
        officialRecordValue: "P",
        sequence: 1,
      },
      {
        id: "band-ministry-incomplete",
        tenantId: "cca-main",
        scaleId: "scale-ministry-pass-fail",
        label: "Incomplete",
        isPassing: false,
        isCompletion: false,
        officialRecordValue: "I",
        sequence: 2,
      },
    ],
    ruleSets: [
      {
        id: "ruleset-acts-ministry-completion",
        tenantId: "cca-main",
        courseId: "course-acts-ministry",
        sectionId: "section-acts-ministry",
        evaluationType: "pass_fail",
        scaleId: "scale-ministry-pass-fail",
        recordType: "completion_record",
        gpaPolicy: "not_applicable",
        creditPolicy: "not_applicable",
        clockHourPolicy: "attempted_and_earned",
        competencyPolicy: "not_applicable",
        narrativePolicy: "optional",
        postingPolicy: "registrar_posting",
        lmsGradeReturnPolicy: "manual_entry_only",
        status: "active",
        createdAt: "2026-04-23T09:00:00.000Z",
        updatedAt: "2026-04-23T09:00:00.000Z",
      },
    ],
    officialRecordRules: [
      {
        id: "record-ministry-completion",
        tenantId: "cca-main",
        recordType: "completion_record",
        appliesToInstitutionMode: "mixed",
        postingAuthority: "registrar",
        releasePolicy: "registrar_release",
        includedInTranscript: false,
        includedInProgressReport: false,
        includedInCompletionRecord: true,
        includedInPromotion: false,
        includedInGraduationAudit: true,
        status: "active",
      },
    ],
    standingRules: [
      {
        id: "standing-ministry-completion-ready",
        tenantId: "cca-main",
        name: "Ministry Completion Ready",
        standingType: "graduation_ready",
        appliesToInstitutionMode: "mixed",
        minimumClockHours: 24,
        requiredCompletionRecords: ["course-acts-ministry"],
        graduationCriteria: "Acts ministry module completion and 24 clock hours posted.",
        status: "active",
      },
    ],
  },
  peopleConfiguration: {
    institutionProfile: createInstitutionProfileDefaults({
      tenantId: "cca-main",
      institutionName: "ChurchCore Academy",
      legalName: "ChurchCore Academy",
      primaryMode: "childrens_school",
      supportedModes: ["childrens_school", "bible_school"],
      lmsProvider: "none",
      now: "2026-04-23T09:00:00.000Z",
    }),
    people: [
      {
        id: "person-lena-rivera",
        tenantId: "cca-main",
        displayName: "Lena Rivera",
        givenName: "Lena",
        familyName: "Rivera",
        email: "lena.rivera@churchcoreacademy.edu",
        dateOfBirth: "2017-04-10",
        personStatus: "active",
        createdAt: "2026-04-23T09:00:00.000Z",
        updatedAt: "2026-04-23T09:00:00.000Z",
      },
      {
        id: "person-marisol-rivera",
        tenantId: "cca-main",
        displayName: "Marisol Rivera",
        givenName: "Marisol",
        familyName: "Rivera",
        email: "marisol.rivera@example.com",
        phone: "555-0101",
        personStatus: "active",
        createdAt: "2026-04-23T09:00:00.000Z",
        updatedAt: "2026-04-23T09:00:00.000Z",
      },
      {
        id: "person-sophia-marsh",
        tenantId: "cca-main",
        displayName: "Sophia Marsh",
        givenName: "Sophia",
        familyName: "Marsh",
        email: "sophia.marsh@churchcoreacademy.edu",
        personStatus: "active",
        createdAt: "2026-04-23T09:00:00.000Z",
        updatedAt: "2026-04-23T09:00:00.000Z",
      },
      {
        id: "person-regina-holt",
        tenantId: "cca-main",
        displayName: "Regina Holt",
        givenName: "Regina",
        familyName: "Holt",
        email: "regina.holt@churchcoreacademy.edu",
        personStatus: "active",
        createdAt: "2026-04-23T09:00:00.000Z",
        updatedAt: "2026-04-23T09:00:00.000Z",
      },
      {
        id: "person-julian-pace",
        tenantId: "cca-main",
        displayName: "Julian Pace",
        givenName: "Julian",
        familyName: "Pace",
        email: "julian.pace@churchcoreacademy.edu",
        personStatus: "active",
        createdAt: "2026-04-23T09:00:00.000Z",
        updatedAt: "2026-04-23T09:00:00.000Z",
      },
    ],
    roleAssignments: [
      {
        id: "role-lena-student",
        tenantId: "cca-main",
        personId: "person-lena-rivera",
        role: "student",
        scopeType: "tenant",
        status: "active",
        startsOn: "2026-08-15",
        createdAt: "2026-04-23T09:00:00.000Z",
        updatedAt: "2026-04-23T09:00:00.000Z",
      },
      {
        id: "role-marisol-guardian-lena",
        tenantId: "cca-main",
        personId: "person-marisol-rivera",
        role: "guardian",
        scopeType: "student",
        scopeId: "person-lena-rivera",
        status: "active",
        startsOn: "2026-08-15",
        createdAt: "2026-04-23T09:00:00.000Z",
        updatedAt: "2026-04-23T09:00:00.000Z",
      },
      {
        id: "role-sophia-teacher",
        tenantId: "cca-main",
        personId: "person-sophia-marsh",
        role: "teacher",
        scopeType: "tenant",
        status: "active",
        startsOn: "2026-08-15",
        createdAt: "2026-04-23T09:00:00.000Z",
        updatedAt: "2026-04-23T09:00:00.000Z",
      },
      {
        id: "role-regina-registrar",
        tenantId: "cca-main",
        personId: "person-regina-holt",
        role: "registrar",
        scopeType: "tenant",
        status: "active",
        startsOn: "2026-08-15",
        createdAt: "2026-04-23T09:00:00.000Z",
        updatedAt: "2026-04-23T09:00:00.000Z",
      },
      {
        id: "role-julian-advisor",
        tenantId: "cca-main",
        personId: "person-julian-pace",
        role: "advisor",
        scopeType: "tenant",
        status: "active",
        startsOn: "2026-08-15",
        createdAt: "2026-04-23T09:00:00.000Z",
        updatedAt: "2026-04-23T09:00:00.000Z",
      },
    ],
    studentProfiles: [
      {
        id: "student-profile-lena",
        tenantId: "cca-main",
        personId: "person-lena-rivera",
        studentNumber: "CHILD-1001",
        studentType: "child",
        enrollmentStatus: "active",
        primarySubdivisionId: "branch-childrens-school",
        gradeBandSubdivisionId: "grade-band-k5",
        advisorPersonId: "person-julian-pace",
        guardianRequired: true,
        createdAt: "2026-04-23T09:00:00.000Z",
        updatedAt: "2026-04-23T09:00:00.000Z",
      },
    ],
    staffProfiles: [
      {
        id: "staff-profile-sophia",
        tenantId: "cca-main",
        personId: "person-sophia-marsh",
        staffNumber: "STAFF-1001",
        title: "Lead Teacher",
        primaryRole: "teacher",
        primarySubdivisionId: "branch-childrens-school",
        employmentStatus: "active",
        loadPolicy: "children_school_daily_roster",
        createdAt: "2026-04-23T09:00:00.000Z",
        updatedAt: "2026-04-23T09:00:00.000Z",
      },
      {
        id: "staff-profile-regina",
        tenantId: "cca-main",
        personId: "person-regina-holt",
        staffNumber: "STAFF-1002",
        title: "Registrar",
        primaryRole: "registrar",
        employmentStatus: "active",
        createdAt: "2026-04-23T09:00:00.000Z",
        updatedAt: "2026-04-23T09:00:00.000Z",
      },
      {
        id: "staff-profile-julian",
        tenantId: "cca-main",
        personId: "person-julian-pace",
        staffNumber: "STAFF-1003",
        title: "Academic Advisor",
        primaryRole: "advisor",
        employmentStatus: "active",
        createdAt: "2026-04-23T09:00:00.000Z",
        updatedAt: "2026-04-23T09:00:00.000Z",
      },
    ],
    relationships: [
      {
        id: "relationship-lena-marisol",
        tenantId: "cca-main",
        studentPersonId: "person-lena-rivera",
        relatedPersonId: "person-marisol-rivera",
        relationshipType: "guardian",
        authority: "academic_decision",
        visibility: "full_guardian",
        status: "active",
        startsOn: "2026-08-15",
        createdAt: "2026-04-23T09:00:00.000Z",
        updatedAt: "2026-04-23T09:00:00.000Z",
      },
      {
        id: "relationship-lena-sophia",
        tenantId: "cca-main",
        studentPersonId: "person-lena-rivera",
        relatedPersonId: "person-sophia-marsh",
        relationshipType: "mentor",
        authority: "none",
        visibility: "progress",
        status: "active",
        startsOn: "2026-08-15",
        createdAt: "2026-04-23T09:00:00.000Z",
        updatedAt: "2026-04-23T09:00:00.000Z",
      },
      {
        id: "relationship-lena-julian",
        tenantId: "cca-main",
        studentPersonId: "person-lena-rivera",
        relatedPersonId: "person-julian-pace",
        relationshipType: "advisor",
        authority: "registration_decision",
        visibility: "progress",
        status: "active",
        startsOn: "2026-08-15",
        createdAt: "2026-04-23T09:00:00.000Z",
        updatedAt: "2026-04-23T09:00:00.000Z",
      },
    ],
    accountLinks: [
      {
        id: "account-lena-pwa",
        tenantId: "cca-main",
        personId: "person-lena-rivera",
        provider: "supabase_auth",
        externalSubject: "student-lena-rivera",
        status: "active",
        createdAt: "2026-04-23T09:00:00.000Z",
        updatedAt: "2026-04-23T09:00:00.000Z",
      },
      {
        id: "account-marisol-guardian",
        tenantId: "cca-main",
        personId: "person-marisol-rivera",
        provider: "supabase_auth",
        externalSubject: "guardian-marisol-rivera",
        status: "active",
        createdAt: "2026-04-23T09:00:00.000Z",
        updatedAt: "2026-04-23T09:00:00.000Z",
      },
    ],
  },
  administrators: [
    { id: "user-regina", tenantId: "cca-main", name: "Regina Holt", title: "Registrar", role: "registrar" },
    { id: "user-adrian", tenantId: "cca-main", name: "Adrian Wells", title: "Admissions Director", role: "admissions" },
    { id: "user-miriam", tenantId: "cca-main", name: "Miriam Stone", title: "Academic Dean", role: "dean" },
    { id: "user-julian", tenantId: "cca-main", name: "Julian Pace", title: "Academic Advisor", role: "advisor" },
    { id: "user-sophia", tenantId: "cca-main", name: "Sophia Marsh", title: "Academic Administrator", role: "academic_admin" },
  ],
  programs: [
    {
      id: "prog-biblical-studies",
      tenantId: "cca-main",
      name: "B.A. Biblical Studies",
      credential: "bachelor",
      requiredCredits: 120,
      cohortLabel: "Spring 2026 Degree Cohort",
    },
    {
      id: "prog-ministry-leadership",
      tenantId: "cca-main",
      name: "A.A. Ministry Leadership",
      credential: "associate",
      requiredCredits: 60,
      cohortLabel: "Fall 2026 Cohort",
    },
  ],
  students: [
    {
      id: "stu-maya-bennett",
      tenantId: "cca-main",
      fullName: "Maya Bennett",
      email: "maya.bennett@churchcoreacademy.edu",
      enrollmentStatus: "pending",
      applicationStartedAt: "2026-03-28T12:00:00.000Z",
      missingEnrollmentSteps: ["Program assignment", "Advisor assignment", "Final registration confirmation"],
      missingDocuments: ["application_form"],
      documentationNotes: ["Admissions intake checklist is incomplete."],
      creditsEarned: 0,
      expectedCreditsByNow: 0,
      transcriptCredits: 0,
      statusFlag: "pending_review",
      allProgramCoursesCompleted: false,
      graduationAdministrativeHolds: [],
      expectedNextTermRegistered: false,
      transcriptAlerts: [],
      recordAlerts: ["Admitted status has not been posted even though application review is complete."],
    },
    {
      id: "stu-ezra-coleman",
      tenantId: "cca-main",
      fullName: "Ezra Coleman",
      email: "ezra.coleman@churchcoreacademy.edu",
      enrollmentStatus: "admitted",
      admittedAt: "2026-04-02T14:00:00.000Z",
      programId: "prog-ministry-leadership",
      advisorUserId: "user-julian",
      missingEnrollmentSteps: ["Registration agreement"],
      missingDocuments: ["government_id", "prior_transcript", "consent_agreement"],
      documentationNotes: [
        "Transfer transcript has not been received from prior institution.",
        "Student agreement packet remains unsigned.",
      ],
      creditsEarned: 0,
      expectedCreditsByNow: 0,
      transcriptCredits: 0,
      statusFlag: "pending_review",
      allProgramCoursesCompleted: false,
      graduationAdministrativeHolds: [],
      expectedNextTermRegistered: false,
      transcriptAlerts: [],
      recordAlerts: [],
    },
    {
      id: "stu-naomi-price",
      tenantId: "cca-main",
      fullName: "Naomi Price",
      email: "naomi.price@churchcoreacademy.edu",
      enrollmentStatus: "active",
      admittedAt: "2022-08-19T15:00:00.000Z",
      activeTerm: "Spring 2026",
      programId: "prog-biblical-studies",
      advisorUserId: "user-julian",
      missingEnrollmentSteps: [],
      missingDocuments: [],
      documentationNotes: [],
      creditsEarned: 117,
      expectedCreditsByNow: 114,
      transcriptCredits: 117,
      gpa: 3.42,
      statusFlag: "good_standing",
      allProgramCoursesCompleted: true,
      graduationAdministrativeHolds: ["Diploma request confirmation pending"],
      expectedNextTermRegistered: false,
      transcriptAlerts: [],
      recordAlerts: [],
    },
    {
      id: "stu-daniel-hart",
      tenantId: "cca-main",
      fullName: "Daniel Hart",
      email: "daniel.hart@churchcoreacademy.edu",
      enrollmentStatus: "active",
      admittedAt: "2024-01-11T13:00:00.000Z",
      activeTerm: "Spring 2026",
      programId: "prog-biblical-studies",
      advisorUserId: "user-julian",
      missingEnrollmentSteps: [],
      missingDocuments: [],
      documentationNotes: [],
      creditsEarned: 31,
      expectedCreditsByNow: 45,
      transcriptCredits: 31,
      gpa: 1.94,
      statusFlag: "probation",
      allProgramCoursesCompleted: false,
      graduationAdministrativeHolds: [],
      expectedNextTermRegistered: false,
      transcriptAlerts: ["Two incomplete course outcomes remain unresolved."],
      recordAlerts: [],
    },
    {
      id: "stu-leah-brooks",
      tenantId: "cca-main",
      fullName: "Leah Brooks",
      email: "leah.brooks@churchcoreacademy.edu",
      enrollmentStatus: "active",
      admittedAt: "2023-08-15T10:00:00.000Z",
      activeTerm: "Spring 2026",
      programId: "prog-ministry-leadership",
      advisorUserId: "user-julian",
      missingEnrollmentSteps: [],
      missingDocuments: [],
      documentationNotes: [],
      creditsEarned: 48,
      expectedCreditsByNow: 48,
      transcriptCredits: 51,
      gpa: 3.11,
      statusFlag: "good_standing",
      allProgramCoursesCompleted: false,
      graduationAdministrativeHolds: [],
      expectedNextTermRegistered: true,
      transcriptAlerts: [
        "Recorded transcript credits exceed posted program progress by 3 credits.",
        "New Testament Survey appears twice with different completion statuses.",
      ],
      recordAlerts: ["Primary student status and degree audit flag disagree."],
    },
  ],
  faculty: [
    {
      id: "fac-miriam-stone",
      tenantId: "cca-main",
      name: "Miriam Stone",
      title: "Professor of Biblical Studies",
      assignedSectionIds: ["sec-nt401", "sec-ot315", "sec-th210", "sec-ch301", "sec-min210"],
      adviseeCount: 31,
    },
    {
      id: "fac-samuel-reed",
      tenantId: "cca-main",
      name: "Samuel Reed",
      title: "Adjunct Faculty",
      assignedSectionIds: ["sec-ml205"],
      adviseeCount: 8,
    },
  ],
  sections: [
    {
      id: "sec-nt401",
      tenantId: "cca-main",
      code: "NT-401",
      title: "Pauline Epistles",
      programId: "prog-biblical-studies",
      instructorFacultyId: "fac-miriam-stone",
      rosterCount: 29,
      rosterCapacity: 24,
      setupAlerts: [],
    },
    {
      id: "sec-ml205",
      tenantId: "cca-main",
      code: "ML-205",
      title: "Pastoral Administration",
      programId: "prog-ministry-leadership",
      rosterCount: 22,
      rosterCapacity: 20,
      setupAlerts: ["Section syllabus upload pending"],
    },
    {
      id: "sec-cap490",
      tenantId: "cca-main",
      code: "CAP-490",
      title: "Capstone Seminar",
      programId: "prog-biblical-studies",
      rosterCount: 16,
      rosterCapacity: 18,
      setupAlerts: ["No instructor assigned"],
    },
  ],
  thresholds: {
    incompleteEnrollmentDays: 10,
    graduationCreditThreshold: 0.95,
    creditPaceGap: 9,
    minimumGpa: 2,
    facultyLoadThreshold: 4,
    advisorStudentRatioThreshold: 25,
  },
};

export const academyNow = new Date(academyDataset.generatedAt);
