import { PERSONA_KEYS, type PersonaKey } from "../personas";
import type { ApiEntry, PageEntry } from "./types";

// The registry of every page and API method, and who each is for. The coverage gate
// (src/modules/acceptance/__tests__/surface-manifest.test.ts) fails `npm test` when a page or
// API method exists without an entry here, and the sweeps (e2e/sweep/*) check every entry in a
// real browser against a production build. See docs/testing/e2e-suite.md for how to add one.
//
// Access lists name the personas that should get through (see e2e/surfaces/types.ts). They
// encode intended behavior from each route's guard, not just what the app currently does;
// current deviations are tracked in e2e/surfaces/known-issues.ts.
//
// Mutations default to STAFF: the API sweep only asserts the student/guardian/anonymous side of
// a mutation's access (with an empty body), so narrow the list when a journey covers it.

/** Every signed-in persona except the student and guardian portals. */
export const STAFF: readonly PersonaKey[] = PERSONA_KEYS.filter((key) => key !== "student" && key !== "guardian");
export const ALL_SIGNED_IN: readonly PersonaKey[] = PERSONA_KEYS;
/** Faculty-portal roles. */
export const FACULTY: readonly PersonaKey[] = ["faculty", "teacher", "professor"];
/** STUDENT_RECORD_ROLES in src/modules/people/access-policy.ts, as personas in the primary tenant. */
export const STUDENT_RECORDS: readonly PersonaKey[] = ["institutionAdmin", "institutionAdmin2", "registrar", "admissions", "academicAdmin", "dean"];

export const PAGE_MANIFEST: PageEntry[] = [
  { path: "/", access: STAFF, redirectsTo: "/admin" },
  { path: "/admin", access: STAFF },
  { path: "/admin/admissions", access: ["institutionAdmin", "institutionAdmin2", "registrar", "admissions", "dean", "otherTenantAdmin"] },
  { path: "/admin/admissions/decisions", access: ["institutionAdmin", "institutionAdmin2", "registrar", "admissions", "dean", "otherTenantAdmin"] },
  { path: "/admin/admissions/drip-sequences", access: ["institutionAdmin", "institutionAdmin2", "otherTenantAdmin"] },
  { path: "/admin/admissions/inquiries", access: ["institutionAdmin", "institutionAdmin2", "admissions", "otherTenantAdmin"] },
  { path: "/admin/admissions/inquiries/[id]", access: ["institutionAdmin", "institutionAdmin2", "admissions", "otherTenantAdmin"] },
  { path: "/admin/admissions/matriculation", access: ["institutionAdmin", "institutionAdmin2", "registrar", "admissions", "dean", "otherTenantAdmin"] },
  { path: "/admin/alumni", access: ["institutionAdmin", "institutionAdmin2", "registrar", "academicAdmin", "alumniRelations", "otherTenantAdmin"] },
  { path: "/admin/alumni/[personId]", access: ["institutionAdmin", "institutionAdmin2", "registrar", "academicAdmin", "alumniRelations"] },
  { path: "/admin/attendance", access: ["institutionAdmin", "institutionAdmin2", "registrar", "academicAdmin", "dean", "otherTenantAdmin"] },
  { path: "/admin/billing", access: ["institutionAdmin", "institutionAdmin2", "registrar", "finance", "otherTenantAdmin"] },
  { path: "/admin/communications", access: ["institutionAdmin", "institutionAdmin2", "registrar", "finance", "admissions", "academicAdmin", "dean", "otherTenantAdmin"] },
  { path: "/admin/courses", access: ["institutionAdmin", "institutionAdmin2", "registrar", "academicAdmin", "dean", "otherTenantAdmin"] },
  { path: "/admin/denomination", access: ["institutionAdmin", "institutionAdmin2", "registrar", "otherTenantAdmin"] },
  { path: "/admin/denomination/[personId]", access: ["institutionAdmin", "institutionAdmin2", "registrar"] },
  { path: "/admin/faculty", access: ["academicAdmin"] },
  { path: "/admin/financial-aid", access: ["institutionAdmin", "institutionAdmin2", "registrar", "finance", "otherTenantAdmin"] },
  { path: "/admin/formation", access: ["institutionAdmin", "institutionAdmin2", "registrar", "faculty", "advisor", "formationReviewer", "otherTenantAdmin"] },
  { path: "/admin/formation/[studentId]", access: ["institutionAdmin", "institutionAdmin2", "registrar", "formationReviewer"] },
  { path: "/admin/gradebook", access: ["institutionAdmin", "institutionAdmin2", "registrar", "academicAdmin", "dean", "otherTenantAdmin"] },
  { path: "/admin/graduation", access: ["institutionAdmin", "institutionAdmin2", "registrar", "academicAdmin", "dean", "otherTenantAdmin"] },
  { path: "/admin/groups", access: ["institutionAdmin", "institutionAdmin2", "registrar", "academicAdmin", "dean", "otherTenantAdmin"] },
  { path: "/admin/people", access: STAFF, redirectsTo: "/admin/students" },
  { path: "/admin/people/advisors", access: ["institutionAdmin", "institutionAdmin2", "registrar", "academicAdmin", "dean", "otherTenantAdmin"] },
  { path: "/admin/people/advisors/[id]", access: ["institutionAdmin", "institutionAdmin2", "registrar", "academicAdmin", "dean"] },
  { path: "/admin/people/applicants", access: ["institutionAdmin", "institutionAdmin2", "registrar", "admissions", "academicAdmin", "dean", "otherTenantAdmin"] },
  { path: "/admin/people/applicants/[id]", access: ["institutionAdmin", "institutionAdmin2", "registrar", "admissions", "academicAdmin", "dean"] },
  { path: "/admin/people/guardians", access: ["institutionAdmin", "institutionAdmin2", "registrar", "admissions", "academicAdmin", "dean", "otherTenantAdmin"] },
  { path: "/admin/people/guardians/[id]", access: ["institutionAdmin", "institutionAdmin2", "registrar", "admissions", "academicAdmin", "dean"] },
  { path: "/admin/people/staff", access: ["institutionAdmin", "institutionAdmin2", "registrar", "admissions", "academicAdmin", "dean", "otherTenantAdmin"] },
  { path: "/admin/people/staff/[id]", access: ["institutionAdmin", "institutionAdmin2", "registrar", "admissions", "academicAdmin", "dean"] },
  { path: "/admin/people/students", access: ["institutionAdmin", "institutionAdmin2", "registrar", "admissions", "academicAdmin", "dean", "otherTenantAdmin"] },
  { path: "/admin/people/students/[id]", access: ["institutionAdmin", "institutionAdmin2", "registrar", "admissions", "academicAdmin", "dean"] },
  { path: "/admin/programs", access: ["institutionAdmin", "institutionAdmin2", "registrar", "academicAdmin", "dean", "otherTenantAdmin"] },
  { path: "/admin/programs/[id]", access: ["institutionAdmin", "institutionAdmin2", "registrar", "admissions", "academicAdmin", "dean"] },
  { path: "/admin/programs/new", access: ["institutionAdmin", "institutionAdmin2", "registrar", "academicAdmin", "dean", "otherTenantAdmin"] },
  { path: "/admin/reporting", access: ["institutionAdmin", "institutionAdmin2", "registrar", "finance", "academicAdmin", "dean", "otherTenantAdmin"] },
  { path: "/admin/sections", access: ["institutionAdmin", "institutionAdmin2", "registrar", "academicAdmin", "dean", "otherTenantAdmin"] },
  { path: "/admin/settings/calendar", access: ["institutionAdmin", "institutionAdmin2", "registrar", "academicAdmin", "dean", "otherTenantAdmin"] },
  { path: "/admin/settings/calendar/years/[id]", access: ["institutionAdmin", "institutionAdmin2", "registrar", "academicAdmin", "dean"] },
  { path: "/admin/settings/compliance", access: ["institutionAdmin", "institutionAdmin2", "registrar", "academicAdmin", "dean", "otherTenantAdmin"] },
  { path: "/admin/settings/courses", access: ["institutionAdmin", "institutionAdmin2", "registrar", "academicAdmin", "dean", "otherTenantAdmin"] },
  { path: "/admin/settings/grading", access: ["institutionAdmin", "institutionAdmin2", "registrar", "academicAdmin", "dean", "otherTenantAdmin"] },
  { path: "/admin/settings/institution", access: ["institutionAdmin", "institutionAdmin2", "registrar", "academicAdmin", "dean", "otherTenantAdmin"] },
  { path: "/admin/settings/lms", access: ["institutionAdmin", "institutionAdmin2", "registrar", "academicAdmin", "dean", "otherTenantAdmin"] },
  { path: "/admin/settings/people", access: STAFF, redirectsTo: "/admin/students" },
  { path: "/admin/staff", access: ["institutionAdmin", "institutionAdmin2", "registrar", "admissions", "academicAdmin", "dean", "otherTenantAdmin"] },
  { path: "/admin/students", access: ["institutionAdmin", "institutionAdmin2", "registrar", "admissions", "academicAdmin", "dean", "otherTenantAdmin"] },
  { path: "/admin/students/[id]", access: ["institutionAdmin", "institutionAdmin2", "registrar", "admissions", "academicAdmin", "dean"] },
  { path: "/admin/transcripts", access: ["institutionAdmin", "institutionAdmin2", "registrar", "academicAdmin", "dean", "otherTenantAdmin"] },
  { path: "/admin/workflows", access: ["academicAdmin"] },
  { path: "/admin/workflows/watchlist", access: ["institutionAdmin", "institutionAdmin2", "registrar", "faculty", "academicAdmin", "advisor", "otherTenantAdmin"] },
  { path: "/admissions", access: STAFF, redirectsTo: "/admin/admissions" },
  { path: "/apply", access: "public" },
  { path: "/apply/status", access: "public" },
  { path: "/dashboard/admin/gradebook", access: ALL_SIGNED_IN },
  { path: "/dashboard/faculty/gradebook", access: ALL_SIGNED_IN },
  { path: "/dashboard/instructor/gradebook", access: STAFF, redirectsTo: "/dashboard/faculty/gradebook" },
  { path: "/dashboard/learner/grades", access: STAFF, redirectsTo: "/dashboard/student/grades" },
  { path: "/dashboard/student/grades", access: ALL_SIGNED_IN },
  { path: "/faculty", access: ALL_SIGNED_IN },
  { path: "/faculty/attendance", access: ALL_SIGNED_IN },
  { path: "/faculty/gradebook", access: ALL_SIGNED_IN },
  { path: "/faculty/gradebook/[sectionId]", access: ALL_SIGNED_IN },
  { path: "/faculty/gradebook/[sectionId]/assignments/[assignmentId]", access: ["institutionAdmin", "institutionAdmin2", "registrar", "faculty", "teacher", "academicAdmin", "dean", "professor"] },
  { path: "/faculty/gradebook/[sectionId]/assignments/new", access: ALL_SIGNED_IN },
  { path: "/faculty/gradebook/[sectionId]/computed", access: ["institutionAdmin", "institutionAdmin2", "registrar", "teacher", "academicAdmin", "dean"] },
  { path: "/faculty/roster", access: ALL_SIGNED_IN },
  { path: "/faculty/schedule", access: FACULTY },
  { path: "/faculty/sections", access: FACULTY },
  { path: "/faculty/shepherd", access: FACULTY },
  { path: "/guardian", access: ALL_SIGNED_IN },
  { path: "/guardian/[studentId]", access: ["guardian"] },
  { path: "/guardian/messages", access: ALL_SIGNED_IN },
  { path: "/hq", access: STAFF, redirectsTo: "/internal/hq" },
  { path: "/internal/hq", access: ALL_SIGNED_IN },
  { path: "/login", access: "public" },
  { path: "/platform/control", access: ["institutionAdmin"] },
  { path: "/programs", access: STAFF, redirectsTo: "/admin/programs" },
  { path: "/programs/[id]", access: STAFF, redirectsTo: "/admin/programs" },
  { path: "/settings/calendar", access: STAFF, redirectsTo: "/admin/settings/calendar" },
  { path: "/settings/courses", access: STAFF, redirectsTo: "/admin/settings/courses" },
  { path: "/settings/demo-feedback", access: ALL_SIGNED_IN },
  { path: "/settings/grading", access: STAFF, redirectsTo: "/admin/settings/grading" },
  { path: "/settings/institution", access: STAFF, redirectsTo: "/admin/settings/institution" },
  { path: "/settings/people", access: STAFF, redirectsTo: "/admin/students" },
  { path: "/student", access: ["student"] },
  { path: "/student/account", access: ["student"] },
  { path: "/student/aid", access: ["student"] },
  { path: "/student/attendance", access: ["student"] },
  { path: "/student/courses", access: ["student"] },
  { path: "/student/documents", access: ["student"] },
  { path: "/student/formation", access: ["student"] },
  { path: "/student/lms", access: ["student"] },
  { path: "/student/messages", access: ["student"] },
  { path: "/student/offline", access: ["student"] },
  { path: "/student/privacy", access: ["student"] },
  { path: "/student/progress", access: ["student"] },
  { path: "/student/schedule", access: ["student"] },
  { path: "/students", access: STAFF, redirectsTo: "/admin/students" },
  { path: "/students/[id]", access: STAFF, redirectsTo: "/admin/students" },
  { path: "/workflows", access: STAFF, redirectsTo: "/admin/workflows" },
];

export const API_MANIFEST: ApiEntry[] = [
  { path: "/api/academy/admissions/applications", methods: { GET: ["institutionAdmin", "institutionAdmin2", "registrar", "admissions", "dean", "otherTenantAdmin"], POST: STAFF } },
  { path: "/api/academy/admissions/applications/[id]", methods: { GET: ["institutionAdmin", "institutionAdmin2", "registrar", "admissions", "dean", "otherTenantAdmin"] } },
  { path: "/api/academy/admissions/applications/[id]/agreement", methods: { GET: ALL_SIGNED_IN } },
  { path: "/api/academy/admissions/applications/[id]/convert", methods: { POST: STAFF } },
  { path: "/api/academy/admissions/applications/[id]/decision", methods: { POST: STAFF } },
  { path: "/api/academy/admissions/applications/[id]/documents", methods: { GET: ALL_SIGNED_IN } },
  { path: "/api/academy/admissions/applications/[id]/documents/[itemId]", methods: { PATCH: STAFF } },
  { path: "/api/academy/admissions/applications/[id]/documents/[itemId]/upload-url", methods: { POST: STAFF } },
  { path: "/api/academy/admissions/applications/[id]/enrollment-confirmation", methods: { POST: STAFF } },
  { path: "/api/academy/admissions/applications/[id]/fee", methods: { GET: ["institutionAdmin", "institutionAdmin2", "registrar", "admissions", "academicAdmin", "dean", "otherTenantAdmin"] } },
  { path: "/api/academy/admissions/applications/[id]/fee/pay", methods: { POST: STAFF } },
  { path: "/api/academy/admissions/applications/[id]/fee/waive", methods: { POST: STAFF } },
  { path: "/api/academy/admissions/applications/[id]/submit", methods: { POST: STAFF } },
  { path: "/api/academy/admissions/conversion-funnel", methods: { GET: ["institutionAdmin", "institutionAdmin2", "admissions", "otherTenantAdmin"] } },
  { path: "/api/academy/admissions/drip-sequences", methods: { GET: ["institutionAdmin", "institutionAdmin2", "otherTenantAdmin"], POST: STAFF } },
  { path: "/api/academy/admissions/inquiries", methods: { GET: ["institutionAdmin", "institutionAdmin2", "admissions", "otherTenantAdmin"], POST: STAFF } },
  { path: "/api/academy/admissions/inquiries/[id]", methods: { PATCH: STAFF } },
  { path: "/api/academy/admissions/inquiries/[id]/convert", methods: { POST: STAFF } },
  { path: "/api/academy/admissions/inquiries/[id]/trigger-drip", methods: { POST: STAFF } },
  { path: "/api/academy/admissions/programs/[programId]/requirements", methods: { GET: ALL_SIGNED_IN, POST: STAFF } },
  { path: "/api/academy/admissions/programs/[programId]/requirements/[reqId]", methods: { DELETE: STAFF } },
  { path: "/api/academy/alumni", methods: { GET: ["institutionAdmin", "institutionAdmin2", "registrar", "academicAdmin", "alumniRelations", "otherTenantAdmin"], POST: STAFF } },
  { path: "/api/academy/alumni-roster", methods: { GET: ["institutionAdmin", "institutionAdmin2", "registrar", "academicAdmin", "alumniRelations", "otherTenantAdmin"] } },
  { path: "/api/academy/alumni/[id]", methods: { PATCH: STAFF } },
  { path: "/api/academy/alumni/[id]/gifts", methods: { GET: ["institutionAdmin", "institutionAdmin2", "registrar", "academicAdmin", "alumniRelations", "otherTenantAdmin"], POST: STAFF } },
  { path: "/api/academy/alumni/gifts/[giftId]/acknowledge", methods: { POST: STAFF } },
  { path: "/api/academy/alumni/giving-summary", methods: { GET: ["institutionAdmin", "institutionAdmin2", "registrar", "academicAdmin", "otherTenantAdmin"] } },
  { path: "/api/academy/attendance", methods: { GET: ALL_SIGNED_IN, POST: STAFF } },
  { path: "/api/academy/attendance/signals", methods: { POST: STAFF } },
  { path: "/api/academy/attendance/threshold-status", methods: { GET: ["institutionAdmin", "institutionAdmin2", "registrar", "faculty", "teacher", "student", "academicAdmin", "dean", "professor", "otherTenantAdmin"] } },
  { path: "/api/academy/billing", methods: { GET: ALL_SIGNED_IN, POST: STAFF } },
  { path: "/api/academy/billing/checkout", methods: { POST: STAFF } },
  { path: "/api/academy/billing/payment-link", methods: { POST: STAFF } },
  { path: "/api/academy/billing/payment-plans", methods: { POST: STAFF } },
  { path: "/api/academy/billing/stripe-webhook", methods: { POST: "webhook" } },
  { path: "/api/academy/billing/tuition-schedules", methods: { GET: ["institutionAdmin", "institutionAdmin2", "registrar", "finance", "otherTenantAdmin"], POST: STAFF } },
  { path: "/api/academy/billing/tuition-schedules/[id]", methods: { DELETE: STAFF } },
  { path: "/api/academy/calendar/periods", methods: { GET: ALL_SIGNED_IN } },
  { path: "/api/academy/calendar/periods/[id]", methods: { DELETE: STAFF } },
  { path: "/api/academy/calendar/terms", methods: { POST: STAFF } },
  { path: "/api/academy/calendar/terms/[id]", methods: { PATCH: STAFF, DELETE: STAFF } },
  { path: "/api/academy/calendar/terms/[id]/archive", methods: { PATCH: STAFF } },
  { path: "/api/academy/calendar/terms/[id]/close", methods: { POST: STAFF } },
  { path: "/api/academy/calendar/terms/[id]/periods", methods: { POST: STAFF } },
  { path: "/api/academy/calendar/terms/[id]/periods/[periodId]", methods: { PATCH: STAFF } },
  { path: "/api/academy/calendar/terms/[id]/periods/[periodId]/archive", methods: { PATCH: STAFF } },
  { path: "/api/academy/calendar/terms/[id]/periods/[periodId]/status", methods: { PATCH: STAFF } },
  { path: "/api/academy/calendar/terms/[id]/section-count", methods: { GET: ALL_SIGNED_IN } },
  { path: "/api/academy/calendar/terms/[id]/status", methods: { PATCH: STAFF } },
  { path: "/api/academy/calendar/years", methods: { GET: ALL_SIGNED_IN, POST: STAFF } },
  { path: "/api/academy/calendar/years/[id]", methods: { GET: ALL_SIGNED_IN, PATCH: STAFF, DELETE: STAFF } },
  { path: "/api/academy/calendar/years/[id]/periods", methods: { POST: STAFF } },
  { path: "/api/academy/calendar/years/[id]/periods/[periodId]", methods: { PATCH: STAFF, DELETE: STAFF } },
  { path: "/api/academy/calendar/years/[id]/periods/[periodId]/status", methods: { PATCH: STAFF } },
  { path: "/api/academy/campuses", methods: { GET: ["institutionAdmin", "institutionAdmin2", "registrar", "faculty", "student", "academicAdmin", "advisor", "otherTenantAdmin"], POST: STAFF } },
  { path: "/api/academy/campuses/[id]", methods: { PATCH: STAFF } },
  { path: "/api/academy/campuses/[id]/set-primary", methods: { POST: STAFF } },
  { path: "/api/academy/communications", methods: { GET: ALL_SIGNED_IN, POST: STAFF, PATCH: STAFF } },
  { path: "/api/academy/communications/triggers", methods: { GET: ALL_SIGNED_IN, POST: STAFF } },
  { path: "/api/academy/conduct", methods: { POST: STAFF } },
  { path: "/api/academy/conduct/[id]", methods: { GET: ["institutionAdmin", "institutionAdmin2", "registrar", "academicAdmin", "advisor", "otherTenantAdmin"], PATCH: STAFF } },
  { path: "/api/academy/conduct/[id]/appeal", methods: { POST: STAFF } },
  { path: "/api/academy/conduct/[id]/interventions", methods: { POST: STAFF } },
  { path: "/api/academy/conduct/interventions/[id]", methods: { PATCH: STAFF } },
  { path: "/api/academy/config/calendar", methods: { GET: ["institutionAdmin", "institutionAdmin2", "registrar", "academicAdmin", "dean", "otherTenantAdmin"] } },
  { path: "/api/academy/config/courses", methods: { GET: ["institutionAdmin", "institutionAdmin2", "registrar", "academicAdmin", "dean", "otherTenantAdmin"] } },
  { path: "/api/academy/config/grading", methods: { GET: ["institutionAdmin", "institutionAdmin2", "registrar", "academicAdmin", "dean", "otherTenantAdmin"] } },
  { path: "/api/academy/config/grading/official-record-rules", methods: { POST: STAFF } },
  { path: "/api/academy/config/grading/official-record-rules/[id]", methods: { PATCH: STAFF, DELETE: STAFF } },
  { path: "/api/academy/config/grading/rule-sets", methods: { POST: STAFF } },
  { path: "/api/academy/config/grading/rule-sets/[id]", methods: { PATCH: STAFF, DELETE: STAFF } },
  { path: "/api/academy/config/grading/scale-bands", methods: { POST: STAFF } },
  { path: "/api/academy/config/grading/scale-bands/[id]", methods: { PATCH: STAFF, DELETE: STAFF } },
  { path: "/api/academy/config/grading/scales", methods: { POST: STAFF } },
  { path: "/api/academy/config/grading/scales/[id]", methods: { PATCH: STAFF, DELETE: STAFF } },
  { path: "/api/academy/config/institution", methods: { GET: ["institutionAdmin", "institutionAdmin2", "registrar", "academicAdmin", "dean", "otherTenantAdmin"], PATCH: STAFF } },
  { path: "/api/academy/courses", methods: { GET: ALL_SIGNED_IN, POST: STAFF } },
  { path: "/api/academy/courses/[id]", methods: { GET: ["institutionAdmin", "institutionAdmin2", "registrar", "faculty", "teacher", "finance", "admissions", "student", "guardian", "academicAdmin", "dean", "advisor", "professor", "alumniRelations", "formationReviewer"], PATCH: STAFF, DELETE: STAFF } },
  { path: "/api/academy/courses/[id]/activate", methods: { POST: STAFF } },
  { path: "/api/academy/courses/[id]/archive", methods: { PATCH: STAFF } },
  { path: "/api/academy/courses/[id]/sections", methods: { GET: ["institutionAdmin", "institutionAdmin2", "registrar", "faculty", "teacher", "finance", "admissions", "student", "guardian", "academicAdmin", "dean", "advisor", "professor", "alumniRelations", "formationReviewer"], POST: STAFF } },
  { path: "/api/academy/courses/[id]/sections/[sectionId]", methods: { PATCH: STAFF } },
  { path: "/api/academy/courses/[id]/sections/[sectionId]/status", methods: { PATCH: STAFF } },
  { path: "/api/academy/demo-feedback", methods: { POST: STAFF } },
  { path: "/api/academy/denomination-roster", methods: { GET: ["institutionAdmin", "institutionAdmin2", "registrar", "otherTenantAdmin"] } },
  { path: "/api/academy/financial-aid", methods: { GET: ALL_SIGNED_IN, POST: STAFF } },
  { path: "/api/academy/financial-aid/[id]/decision", methods: { POST: STAFF } },
  { path: "/api/academy/financial-aid/[id]/generate-letter", methods: { POST: STAFF } },
  { path: "/api/academy/financial-aid/[id]/letter-url", methods: { GET: ALL_SIGNED_IN } },
  { path: "/api/academy/financial-aid/federal-disbursements", methods: { GET: ALL_SIGNED_IN, POST: STAFF } },
  { path: "/api/academy/financial-aid/federal-disbursements/[id]", methods: { PATCH: STAFF } },
  { path: "/api/academy/financial-aid/federal-programs", methods: { GET: ["institutionAdmin", "institutionAdmin2", "registrar", "finance", "otherTenantAdmin"], POST: STAFF } },
  { path: "/api/academy/gradebook/assignments", methods: { POST: STAFF } },
  { path: "/api/academy/gradebook/assignments/[id]", methods: { DELETE: STAFF } },
  { path: "/api/academy/gradebook/assignments/[id]/scores", methods: { PUT: STAFF } },
  { path: "/api/academy/gradebook/records", methods: { GET: ["institutionAdmin", "institutionAdmin2", "registrar", "faculty", "teacher", "student", "academicAdmin", "dean", "professor", "otherTenantAdmin"], POST: STAFF } },
  { path: "/api/academy/guardian/students", methods: { GET: ["guardian"] } },
  { path: "/api/academy/guardian/students/[studentId]", methods: { GET: ["guardian"] } },
  { path: "/api/academy/guardian/students/[studentId]/attendance", methods: { GET: ["guardian"] } },
  { path: "/api/academy/guardian/students/[studentId]/billing", methods: { GET: ["guardian"] } },
  { path: "/api/academy/guardian/students/[studentId]/ferpa", methods: { PATCH: ["guardian"] } },
  { path: "/api/academy/guardian/students/[studentId]/grades", methods: { GET: ["guardian"] } },
  { path: "/api/academy/guardian/students/[studentId]/notification-preferences", methods: { PATCH: ["guardian"] } },
  { path: "/api/academy/learner-intelligence/consent", methods: { GET: ALL_SIGNED_IN, POST: STAFF, DELETE: STAFF } },
  { path: "/api/academy/learner-intelligence/events", methods: { POST: STAFF } },
  { path: "/api/academy/learner-intelligence/interventions", methods: { GET: ["institutionAdmin", "institutionAdmin2", "registrar", "faculty", "teacher", "academicAdmin", "dean", "advisor", "professor", "otherTenantAdmin"] } },
  { path: "/api/academy/learner-intelligence/interventions/[id]/history", methods: { GET: ["institutionAdmin", "institutionAdmin2", "registrar", "faculty", "teacher", "academicAdmin", "dean", "advisor", "professor", "otherTenantAdmin"] } },
  { path: "/api/academy/learner-intelligence/interventions/[id]/status", methods: { POST: STAFF } },
  { path: "/api/academy/learner-intelligence/memory", methods: { GET: ALL_SIGNED_IN } },
  { path: "/api/academy/lms/contract", methods: { GET: ["institutionAdmin", "institutionAdmin2"], POST: STAFF } },
  { path: "/api/academy/lms/oneroster-package", methods: { GET: ["institutionAdmin", "institutionAdmin2", "otherTenantAdmin"] } },
  { path: "/api/academy/lms/readiness", methods: { GET: ["institutionAdmin", "institutionAdmin2", "registrar", "academicAdmin", "dean", "otherTenantAdmin"], POST: STAFF } },
  { path: "/api/academy/lms/sections/[sectionId]/roster-plan", methods: { POST: STAFF } },
  { path: "/api/academy/ministry-formation/[studentId]", methods: { GET: ["institutionAdmin", "institutionAdmin2", "registrar", "student", "formationReviewer", "otherTenantAdmin"] } },
  { path: "/api/academy/ministry-formation/assign-advisor", methods: { POST: STAFF } },
  { path: "/api/academy/ministry-formation/endorse", methods: { POST: STAFF } },
  { path: "/api/academy/ministry-formation/evaluations", methods: { POST: STAFF } },
  { path: "/api/academy/ministry-formation/grant-reviewer", methods: { POST: STAFF } },
  { path: "/api/academy/ministry-formation/milestones", methods: { POST: STAFF } },
  { path: "/api/academy/ministry-formation/practicum", methods: { POST: STAFF } },
  { path: "/api/academy/ministry-formation/revoke-reviewer", methods: { POST: STAFF } },
  { path: "/api/academy/ministry-formation/students", methods: { GET: ["institutionAdmin", "institutionAdmin2", "registrar", "faculty", "advisor", "formationReviewer", "otherTenantAdmin"] } },
  { path: "/api/academy/people/[id]/denomination-memberships", methods: { GET: ["institutionAdmin", "institutionAdmin2", "registrar", "student", "advisor"], POST: STAFF } },
  { path: "/api/academy/people/[id]/denomination-memberships/[membershipId]", methods: { PATCH: STAFF } },
  { path: "/api/academy/people/[id]/ordinations", methods: { GET: ["institutionAdmin", "institutionAdmin2", "registrar", "student", "advisor"], POST: STAFF } },
  { path: "/api/academy/people/[id]/ordinations/[ordinationId]", methods: { PATCH: STAFF } },
  { path: "/api/academy/people/role-assignments", methods: { POST: STAFF } },
  { path: "/api/academy/platform/demo-feedback", methods: { GET: ["institutionAdmin"] } },
  { path: "/api/academy/platform/demo-feedback/[id]", methods: { PATCH: STAFF } },
  { path: "/api/academy/programs", methods: { GET: ALL_SIGNED_IN, POST: STAFF } },
  { path: "/api/academy/programs/[id]", methods: { GET: ALL_SIGNED_IN, PATCH: STAFF, DELETE: STAFF } },
  { path: "/api/academy/programs/[id]/curriculum", methods: { GET: ALL_SIGNED_IN, PUT: STAFF } },
  { path: "/api/academy/registrations", methods: { GET: ALL_SIGNED_IN, POST: STAFF } },
  { path: "/api/academy/registrations/[id]", methods: { PATCH: STAFF, DELETE: STAFF } },
  { path: "/api/academy/reporting/accreditation", methods: { GET: ["institutionAdmin", "institutionAdmin2", "otherTenantAdmin"], POST: STAFF } },
  { path: "/api/academy/reporting/accreditation/[id]/compile", methods: { POST: STAFF } },
  { path: "/api/academy/reporting/accreditation/[id]/url", methods: { GET: ["institutionAdmin", "institutionAdmin2", "otherTenantAdmin"] } },
  { path: "/api/academy/reporting/ipeds", methods: { GET: ["institutionAdmin", "institutionAdmin2", "registrar", "finance", "academicAdmin", "dean", "otherTenantAdmin"] } },
  { path: "/api/academy/reports", methods: { GET: ["institutionAdmin", "institutionAdmin2", "registrar", "finance", "academicAdmin", "dean", "otherTenantAdmin"] } },
  { path: "/api/academy/reports/compliance", methods: { GET: ["institutionAdmin", "institutionAdmin2", "registrar", "academicAdmin", "otherTenantAdmin"], POST: STAFF } },
  { path: "/api/academy/reports/compliance/[id]", methods: { GET: ["institutionAdmin", "institutionAdmin2", "registrar", "academicAdmin", "otherTenantAdmin"] } },
  { path: "/api/academy/reports/compliance/[id]/advance", methods: { POST: STAFF } },
  { path: "/api/academy/sections", methods: { POST: STAFF } },
  { path: "/api/academy/sections/[id]", methods: { PATCH: STAFF, DELETE: STAFF } },
  { path: "/api/academy/sections/[id]/assignments", methods: { GET: ["institutionAdmin", "institutionAdmin2", "registrar", "faculty", "teacher", "academicAdmin", "dean", "professor"], POST: STAFF } },
  { path: "/api/academy/sections/[id]/assignments/[assignmentId]", methods: { PATCH: STAFF } },
  { path: "/api/academy/sections/[id]/assignments/[assignmentId]/grades", methods: { GET: ["institutionAdmin", "institutionAdmin2", "registrar", "faculty", "teacher", "academicAdmin", "dean", "professor"], POST: STAFF } },
  { path: "/api/academy/sections/[id]/attendance-config", methods: { GET: ["institutionAdmin", "institutionAdmin2", "registrar", "teacher", "academicAdmin", "dean", "otherTenantAdmin"], PATCH: STAFF } },
  { path: "/api/academy/sections/[id]/computed-grades", methods: { GET: ["institutionAdmin", "institutionAdmin2", "registrar", "teacher", "academicAdmin", "dean"] } },
  { path: "/api/academy/sections/[id]/final-grades", methods: { GET: ["institutionAdmin", "institutionAdmin2", "registrar", "teacher", "academicAdmin", "dean"], POST: STAFF } },
  { path: "/api/academy/sections/[id]/instructor", methods: { POST: STAFF } },
  { path: "/api/academy/sections/available", methods: { GET: ALL_SIGNED_IN } },
  { path: "/api/academy/shepherd-ai/evaluate", methods: { POST: STAFF } },
  { path: "/api/academy/shepherd-ai/risk-score", methods: { POST: STAFF } },
  { path: "/api/academy/shepherd-ai/suggestions", methods: { GET: ["academicAdmin"] } },
  { path: "/api/academy/shepherd-ai/suggestions/[id]/defer", methods: { POST: STAFF } },
  { path: "/api/academy/shepherd-ai/suggestions/[id]/dismiss", methods: { POST: STAFF } },
  { path: "/api/academy/shepherd-ai/suggestions/[id]/promote", methods: { POST: STAFF } },
  { path: "/api/academy/shepherd-ai/suggestions/[id]/snooze", methods: { POST: STAFF } },
  { path: "/api/academy/shepherd-ai/watchlist", methods: { GET: ["institutionAdmin", "institutionAdmin2", "registrar", "faculty", "academicAdmin", "advisor", "otherTenantAdmin"] } },
  { path: "/api/academy/staff/[id]", methods: { PATCH: STAFF } },
  { path: "/api/academy/staff/invite", methods: { POST: STAFF } },
  { path: "/api/academy/student-groups", methods: { GET: ["institutionAdmin", "institutionAdmin2", "registrar", "academicAdmin", "dean", "otherTenantAdmin"], POST: STAFF } },
  { path: "/api/academy/student-groups/[id]", methods: { PATCH: STAFF } },
  { path: "/api/academy/student-groups/[id]/members", methods: { GET: ["institutionAdmin", "institutionAdmin2", "registrar", "academicAdmin", "dean", "otherTenantAdmin"], POST: STAFF } },
  { path: "/api/academy/student-groups/[id]/members/[membershipId]", methods: { DELETE: STAFF } },
  { path: "/api/academy/student/lms/launch", methods: { POST: ["student"] } },
  { path: "/api/academy/students", methods: { GET: [...STUDENT_RECORDS, "otherTenantAdmin"] } },
  { path: "/api/academy/students/[id]", methods: { GET: [...STUDENT_RECORDS, "otherTenantAdmin"] } },
  { path: "/api/academy/students/[id]/advisor-notes", methods: { GET: ["institutionAdmin", "institutionAdmin2", "registrar", "faculty", "teacher", "finance", "admissions", "student", "academicAdmin", "dean", "advisor", "professor", "alumniRelations", "formationReviewer", "otherTenantAdmin"] } },
  { path: "/api/academy/students/[id]/conduct", methods: { GET: ["institutionAdmin", "institutionAdmin2", "registrar", "academicAdmin", "advisor", "otherTenantAdmin"] } },
  { path: "/api/academy/students/[id]/enrollment", methods: { PATCH: STAFF } },
  { path: "/api/academy/students/[id]/holds", methods: { GET: ["institutionAdmin", "institutionAdmin2", "registrar", "faculty", "academicAdmin", "dean", "advisor", "otherTenantAdmin"], POST: STAFF } },
  { path: "/api/academy/students/[id]/holds/[holdId]", methods: { PATCH: STAFF } },
  { path: "/api/academy/students/[id]/interventions", methods: { GET: ALL_SIGNED_IN } },
  { path: "/api/academy/students/[id]/notes", methods: { GET: ["institutionAdmin", "institutionAdmin2", "registrar", "faculty", "teacher", "finance", "admissions", "student", "academicAdmin", "dean", "advisor", "professor", "alumniRelations", "formationReviewer", "otherTenantAdmin"], POST: STAFF } },
  { path: "/api/academy/students/[id]/profile", methods: { PATCH: STAFF } },
  { path: "/api/academy/students/[id]/program-membership", methods: { GET: ["institutionAdmin", "institutionAdmin2", "registrar", "academicAdmin", "dean", "otherTenantAdmin"], PUT: STAFF } },
  { path: "/api/academy/students/[id]/program-progress", methods: { GET: ["institutionAdmin", "institutionAdmin2", "registrar", "academicAdmin", "dean", "advisor", "otherTenantAdmin"] } },
  { path: "/api/academy/students/[id]/sap", methods: { GET: ["institutionAdmin", "institutionAdmin2", "registrar", "otherTenantAdmin"], POST: STAFF } },
  { path: "/api/academy/students/[id]/sap/[evalId]/appeal", methods: { PATCH: STAFF } },
  { path: "/api/academy/students/[id]/section-enrollments", methods: { GET: ["institutionAdmin", "institutionAdmin2", "registrar", "academicAdmin", "dean", "otherTenantAdmin"], POST: STAFF } },
  { path: "/api/academy/students/[id]/standing/evaluate", methods: { POST: STAFF } },
  { path: "/api/academy/students/[id]/standing/history", methods: { GET: [] } },
  { path: "/api/academy/students/[id]/status", methods: { PATCH: STAFF } },
  { path: "/api/academy/students/[id]/transcript-entries", methods: { GET: ["institutionAdmin", "institutionAdmin2", "registrar", "academicAdmin", "dean", "otherTenantAdmin"], POST: STAFF } },
  { path: "/api/academy/students/me/billing/pay", methods: { POST: ["student"] } },
  { path: "/api/academy/students/me/contact", methods: { GET: ALL_SIGNED_IN, PATCH: ["student"] } },
  { path: "/api/academy/students/me/notifications", methods: { GET: ALL_SIGNED_IN, PATCH: ALL_SIGNED_IN } },
  { path: "/api/academy/students/me/payment-plan", methods: { GET: ["institutionAdmin", "institutionAdmin2", "registrar", "finance", "student", "otherTenantAdmin"] } },
  { path: "/api/academy/transcripts", methods: { GET: ALL_SIGNED_IN, POST: STAFF } },
  { path: "/api/academy/transcripts/[id]/download", methods: { GET: ALL_SIGNED_IN } },
  { path: "/api/academy/transcripts/[id]/hold", methods: { POST: STAFF } },
  { path: "/api/academy/transcripts/[id]/release", methods: { POST: STAFF } },
  { path: "/api/academy/transcripts/[id]/revoke", methods: { POST: STAFF } },
  { path: "/api/academy/transcripts/request", methods: { POST: STAFF } },
  { path: "/api/academy/user-context", methods: { GET: ALL_SIGNED_IN, PUT: ALL_SIGNED_IN } },
  { path: "/api/academy/workflows", methods: { GET: ["academicAdmin"] } },
  { path: "/api/academy/workflows/[id]/assign", methods: { POST: STAFF } },
  { path: "/api/academy/workflows/[id]/complete", methods: { POST: STAFF } },
  { path: "/api/academy/workflows/[id]/defer", methods: { POST: STAFF } },
  { path: "/api/academy/workflows/[id]/feedback", methods: { POST: STAFF } },
  { path: "/api/admin/people/[id]", methods: { PATCH: STAFF, DELETE: STAFF } },
  { path: "/api/admin/people/[id]/covenant", methods: { GET: ["institutionAdmin", "institutionAdmin2", "registrar", "academicAdmin", "dean"], PUT: STAFF } },
  { path: "/api/ai", methods: { POST: STAFF } },
  { path: "/api/cron/email-worker", methods: { GET: "cron" } },
  { path: "/api/cron/oneroster-delivery", methods: { GET: "cron" } },
  { path: "/api/cron/scheduled-reports", methods: { POST: "cron" } },
  { path: "/api/platform/session", methods: { GET: ["institutionAdmin"] } },
  { path: "/api/platform/tenants", methods: { POST: STAFF } },
  { path: "/api/platform/tenants/[tenantId]/delete", methods: { POST: STAFF } },
  { path: "/api/platform/tenants/select", methods: { POST: STAFF } },
  { path: "/api/public/apply", methods: { POST: "public" } },
  { path: "/api/public/apply/agreement/sign", methods: { POST: "public" } },
  { path: "/api/public/apply/agreement/status", methods: { GET: "public" } },
  { path: "/api/public/apply/documents", methods: { GET: "public" } },
  { path: "/api/public/apply/documents/[itemId]/confirm", methods: { POST: "public" } },
  { path: "/api/public/apply/documents/[itemId]/upload-url", methods: { POST: "public" } },
  { path: "/api/public/apply/fee/pay", methods: { POST: "public" } },
  { path: "/api/public/apply/programs", methods: { GET: "public" } },
  { path: "/api/public/apply/status", methods: { GET: "public" } },
];
