import { FIXTURE_IDS } from "../personas";

// Concrete values for dynamic segments, per route. Records come from migrations or from
// scripts/e2e/seed.ts fixtures. A dynamic segment with no entry here falls back to
// MISSING_ID, so the sweep still checks auth and "no 500" behavior for that route.
// UUID-shaped so uuid-typed routes answer "not found" rather than failing to parse the ID.
export const MISSING_ID = "00000000-0000-4000-8000-00000000dead";

const STUDENT = "person-lena-rivera";

// Samples whose IDs are generated by migrations (so differ per database) are looked up once
// per run by e2e/global-setup.ts and referenced below as "$name".
export const RUNTIME_SAMPLE_QUERIES: Record<string, string> = {
  academicProgramId: "select id from academy_academic_programs where tenant_id = 'cca-main' order by created_at, id limit 1",
  applicationId: "select id from academy_admission_applications where tenant_id = 'cca-main' order by created_at, id limit 1",
};
export const RUNTIME_SAMPLES_FILE = "e2e/.auth/samples.json";

export const PAGE_SAMPLES: Record<string, Record<string, string>> = {
  "/admin/admissions/inquiries/[id]": { id: FIXTURE_IDS.inquiryId },
  "/admin/alumni/[personId]": { personId: FIXTURE_IDS.alumniPersonId },
  "/admin/denomination/[personId]": { personId: STUDENT },
  "/admin/formation/[studentId]": { studentId: STUDENT },
  "/admin/people/advisors/[id]": { id: "person-sophia-marsh" },
  "/admin/people/applicants/[id]": { id: "person-naomi-price" },
  "/admin/people/guardians/[id]": { id: "person-marisol-rivera" },
  "/admin/people/staff/[id]": { id: "person-sophia-marsh" },
  "/admin/people/students/[id]": { id: STUDENT },
  "/admin/programs/[id]": { id: "$academicProgramId" },
  "/admin/settings/calendar/years/[id]": { id: "year-ministry-2026" },
  "/admin/students/[id]": { id: FIXTURE_IDS.studentProfileId },
  "/faculty/gradebook/[sectionId]": { sectionId: FIXTURE_IDS.sectionId },
  "/faculty/gradebook/[sectionId]/assignments/[assignmentId]": { sectionId: FIXTURE_IDS.sectionId, assignmentId: FIXTURE_IDS.assignmentId },
  "/faculty/gradebook/[sectionId]/assignments/new": { sectionId: FIXTURE_IDS.sectionId },
  "/faculty/gradebook/[sectionId]/computed": { sectionId: FIXTURE_IDS.sectionId },
  "/guardian/[studentId]": { studentId: STUDENT },
  "/programs/[id]": { id: "prog-biblical-studies" },
  "/students/[id]": { id: STUDENT },
};

// API samples by path prefix (longest match wins); segments without a rule use MISSING_ID,
// so the route is still checked for auth and "never 5xx" behavior.
const API_SAMPLE_PREFIXES: [string, Record<string, string>][] = [
  ["/api/academy/admissions/applications/[id]", { id: "$applicationId" }],
  ["/api/academy/admissions/inquiries/[id]", { id: FIXTURE_IDS.inquiryId }],
  ["/api/academy/admissions/programs/[programId]", { programId: "prog-biblical-studies" }],
  ["/api/academy/calendar/years/[id]", { id: "year-ministry-2026" }],
  ["/api/academy/courses/[id]", { id: "demo-multi-course-algebra", sectionId: FIXTURE_IDS.sectionId }],
  ["/api/academy/guardian/students/[studentId]", { studentId: STUDENT }],
  ["/api/academy/lms/sections/[sectionId]", { sectionId: FIXTURE_IDS.sectionId }],
  ["/api/academy/ministry-formation/[studentId]", { studentId: STUDENT }],
  ["/api/academy/people/[id]", { id: STUDENT }],
  ["/api/academy/programs/[id]", { id: "$academicProgramId" }],
  ["/api/academy/sections/[id]", { id: FIXTURE_IDS.sectionId, assignmentId: FIXTURE_IDS.assignmentId }],
  ["/api/admin/people/[id]", { id: STUDENT }],
  ["/api/platform/tenants/[tenantId]", { tenantId: "cca-main" }],
];

export const API_SAMPLES: Record<string, Record<string, string>> = new Proxy({}, {
  get(_, pattern: string) {
    const match = API_SAMPLE_PREFIXES.filter(([prefix]) => pattern.startsWith(prefix)).sort((a, b) => b[0].length - a[0].length)[0];
    return match?.[1];
  },
});

export function resolvePath(
  pattern: string,
  samples: Record<string, Record<string, string>>,
  runtime: Record<string, string> = {},
) {
  const values = samples[pattern] ?? {};
  return pattern.replace(/\[([^\]]+)\]/g, (_, name: string) => {
    const value = values[name];
    const resolved = value?.startsWith("$") ? runtime[value.slice(1)] : value;
    return encodeURIComponent(resolved ?? MISSING_ID);
  });
}
